version: '3.8'

services:
  app:
    container_name: bilu_app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: ${STAGE:-dev}
      args:
        - PORT=${APP_PORT:-9150}
    environment:
      - PORT=${APP_PORT:-9150}
    volumes:
      - app:/app

volumes:
  app:
    driver: "local"
